### ISSUE TITLE
Configure video stream

### ISSUE THREAD

**Issue by dlowrey** [CodeSpaceHQ/Telescreen#20]
_As a user, I want Telescreen to stream video of people where I place my cameras so that I can analyze the video frame by frame._

**Tasks**

- [ ]  Write class for starting / accessing video stream
- [ ]  Allow configurations for FPS, PiCamera or USB, Resolution to video stream class
- [ ]  Separate video capture to separate thread
