### ISSUE TITLE
Detect faces in video feed

### ISSUE THREAD

**Issue by dlowrey** [CodeSpaceHQ/Telescreen#21]
_As a user, I want Telescreen to detect faces in the video stream from my cameras so that I can tell when faces are present frame by frame._

**Tasks**

- [ ]  Pull frames from video feed to examine (may need to resize/grayscale/etc)
- [ ]  Run facial detection algorithm on a frame and report back count and location of faces
- [ ]  Keep count of how many faces are present from examined frame to examined frame
- [ ]  Notify (log for now) when the face count increases from previous frame
- [ ]  Research object tracking with `dlib` to help with the above two tasks
