### ISSUE TITLE
Recognize detected faces

### ISSUE THREAD

**Issue by dlowrey** [CodeSpaceHQ/Telescreen#22]
_As a user, I want Telescreen to recognize faces that I have registered in the system so that I can keep track of where they are in the area._

**Tasks**

- [ ] Decide on an optimal facial recognition algorithm to use
- [ ] Decide on a file system / storage plan for recognized people (keep in mind for potential unrecognized people)
- [ ] Implement facial recognition algorithm to run when new face is detected (on that face or on entire frame..?)
