### ISSUE TITLE
Amazon IAM

### ISSUE THREAD

**Issue by camcarlton** [CodeSpaceHQ/Telescreen#53]
_As a user, I would like to have organized the hub and devices with the respects rights so that they don't overreach on their functionality._

**Tasks**

- [ ] Create a user for the hub
- [ ] Creare a user for the telescreen
- [ ] File access + secret key for users
